.gitignore, Jenkinsfile, README.md, docker/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook, notebooktoken, runtest
See this sample build http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/feature%252Fbetter-diagnostic-for-jenkins-build-failure/1/
You can download [`hummingbird.ipynb`](http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/feature%252Fbetter-diagnostic-for-jenkins-build-failure/1/artifact/notebooks/hummingbird.ipynb) and [`hummingbird.ipynb.output.ipynb`](http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/feature%252Fbetter-diagnostic-for-jenkins-build-failure/1/artifact/buildout/hummingbird.ipynb.output.ipynb) for example, then do `nbdiff hummingbird.ipynb hummingbird.ipynb.output.ipynb` (need `conda install nbdime`).  There's still diff for passing notebooks since we had regex to make them pass.
Commit message (is there a way for github to automatically add …
=>  save resulting notebooks to better help troubleshoot errors 

.gitignore, Jenkinsfile, default_build_params, downloadrepos, testall
I needed an environment to run the notebooks from raven.
Might as well get everthing ready here and only step left is to enable
those notebooks to be tested by Jenkins.
The raven notebooks will also need some small tweaks to work properly
under Jenkins.
=> add raven notebooks, download only, not running by Jenkins

Jenkinsfile, binder/Dockerfile, binder/reorg-notebooks, default_build_params, docker/Dockerfile, docker/environment.yml, downloadrepos, launchcontainer, launchnotebook, runtest, testall
Will run them once they all pass, part of https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/issues/13
The ESGF branch is devel and not the usual master because that's what @huard asked.
This PR will lay down the all the ground work to run ESGF notebooks:
* download the ESGF notebooks in Jenkins and also for the auto notebooks deployment to PAVICS and Binder
* publish new Docker image that is able to run ESGF notebooks
* gracefully handle notebook name clash since ESGF notebooks filename are very generic
New Docker image with ability to run ESGF notebooks can then be deployed to our PAVICS instance so we have a public env for everyone to reproduce any possible errors / test fixes.
Few minor fixes to also be ready for Raven notebooks.
Test Jupyter env able to run ESGF notebooks: …
=> Add ESGF notebooks to Jenkins but not running them yet

Jenkinsfile, binder/Dockerfile, launchcontainer, launchnotebook
Same image used for Jenkins testing as well, no new errors on Jenkins http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/refresh-docker-image/2/console
```
<     - xclim==0.10.4b0
>     - xclim==0.10.7b0  
<     - dask==2.1.0
>     - dask==2.2.0
<   - notebook=5.7.8=py36_1
>   - notebook=6.0.0=py36_0
<   - jupyter_server=0.0.5=py36_0
>   - jupyter_server=0.1.1=py36_0
<   - gitpython=2.1.11=py_0
>   - gitpython=3.0.0=py_0
<   - openblas=0.3.6=h6e990d7_4
>   - openblas=0.3.3=h9ac9557_1001
<   - libopenblas=0.3.6=h6e990d7_4
>   - libopenblas=0.3.6=h5a2b251_1
<   - scipy=1.3.0=py36h921218d_0
>   - scipy=1.2.1=py36_blas_openblash1522bff_0
```
=> Refresh Jupyter Server Image for PAVICS

Jenkinsfile, README.md, binder/Dockerfile, docker/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook, releasedocker
Changes hightlight:
Updated:
```
<   - birdhouse-birdy=0.6.2=py_0
>   - birdy=v0.6.5=py_0
<   - owslib=0.17.1b4=py_0  # was from birdhouse channel
>   - owslib=0.18.0=py_0  # now from conda-forge
```
Removed:
```
<   - owslib-esgfwps=0.1.0=py_0  # birdy dropped this dependency I think
```
Full conda env diff:  [env-diff.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/3561311/env-diff.txt)
New conda env export:  [190830.1.env.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/3561316/190830.1.env.txt)
Jupyter test env deployed: https://lvupavics.ouranos.ca/jupyter
=> New Jenkine env / Jupyter docker with new birdy and dropped birdhouse channel

Jenkinsfile, binder/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
Add geopandas and the new request-magpie so notebooks will work with the coming Twitcher/Magpie upgrade (needed to test the Twitcher/Magpie upgrade).
```diff
+  - geopandas=0.6.1=py_1 
request-magpie do not show up anywhere :(
-  - python=3.6.7=h357f687_1005
+  - python=3.7.3=h33d41f4_1
-  - xarray=0.12.3=py_0 
+    - xarray==0.13.0
-    - dask==2.3.0                                                                                                                                
+    - dask==2.6.0
-    - xclim==0.10.8b0                                                                                                                            
+    - xclim==0.11.2
```
Quite a few packages moved from Conda to Pip, ex: xarray, pyproj
Full diff: …
=> Update Jupyter docker image for new and updated packages

docker/environment.yml
Because pypi release now exists and because `conda environment export`
do not show anything install from source so we are losing traceability.
Before:
$ docker run --rm --name testconda -u 0  -it --entrypoint bash pavics/workflow-tests:191106
root@e159d1f12a2e:/# conda env export -n birdy |grep request
- requests=2.22.0=py37_1
After
docker run --rm --name testconda -u 0  -it --entrypoint bash local-build-image
root@170dc125ffc3:/# conda env export -n birdy |grep request
- requests=2.22.0=py37_1
- requests-magpie==0.1.1
=> docker: use requests-magpie from pypi

notebooks/output-sanitize.cfg
To avoid intermittent failure like below due to server performance variation.
```
_________ finch-master/docs/source/notebooks/finch-usage.ipynb::Cell 9 _________
Notebook cell execution failed
Cell 9: Cell outputs differ
Input:
print(log)
Traceback:
mismatch 'stdout'
assert reference_output == test_output failed:
'Processing s...cessfully\n\n' == 'Processing s...cessfully\n\n'
Skipping 281 identical leading characters in diff, use -v to show
- Done |  1.0s
?           ^
+ Done |  1.1s
?           ^
Processing finished successfully
```
Jenkins run: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/more-regex-to-avoid-intermittent-failure/1/console
=> notebooks: add regex for print of wps response log

Jenkinsfile, binder/reorg-notebooks, default_build_params, downloadrepos, testall
Example: download from https://github.com/tlvu/esgf-compute-api instead of
https://github.com/ESGF/esgf-compute-api
For each repo, the user can now specify the branch and the
owner/repo-name on github.
Only limittation is that repo has to be hosted on github.  Everything
else can be customized at Jenkins build request time.
Was needed to test my attempt to fix the ESGF notebooks in this PR https://github.com/ESGF/esgf-compute-api/pull/64
Here is how the new build request page looks like:
Edit:
* add screenshot of "before"
=> jenkins: support downloading repos from a fork

Jenkinsfile, default_build_params, runtest, testall
This is the matching PR for the jenkins-master PR https://github.com/Ouranosinc/jenkins-config/pull/6.
It make use of all the new env var `IS_PROD`, `ENABLE_SCHEDULED_TRIGGER`, and `DEFAULT_PAVICS_HOST`.
I also add the option to feature toogle all the external repos that this repo get all the notebooks to test.
Now we can choose which repo to test its notebooks, instead of having to test all of them.
Advantages:
* More focused/faster test on manual run to only test the repo we are interested in.
* Allow to add new repos that are not ready for nightlies directly to `master` branch (toogle disabled by default) instead of having to have separate branches that require ongoing maintenance to avoid diverging from `master`.  This applies to Raven and ESGF notebooks.
Will delete the 2 branches …
=> Use new env var to customize scheduled trigger and defaut pavics host, also feature toogle external repos

Jenkinsfile, binder/Dockerfile, docker/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
jupyter_bokeh (the extension, not the package) was removed due to this issue https://github.com/bokeh/jupyter_bokeh/issues/93
Era5 Raven notebook PR: https://github.com/Ouranosinc/raven/pull/200
Noticeable  rather large Jupyter env changes:
```diff
<   - birdy=v0.6.5=py_0
>   - birdy=v0.6.6=py_0
<   - bokeh=1.4.0=py36_0
>     - bokeh==2.0.0  # from pip recursive dependencies (we get newer version by not explicitly get from conda !)
<   - esgf-compute-api=2.2.1=py_2
>   - esgf-compute-api=2.2.3=py_0
<   - jupyterlab=1.2.5=py_0
>   - jupyterlab=2.0.1=py_0
<   - owslib=0.19.0=py_2
>   - owslib=0.19.1=py_0
<   - pandas=0.25.3=py36hb3f55d8_0
>   - pandas=1.0.1=py37hb3f55d8_0
<   - python=3.6.7=h357f687_1006
>   - python=3.7.6=h357f687_4_cpython
>   - regionmask=0.5.0=py_1
<   - …
```
=> docker: add regionmask and salem for Era5 Raven notebooks, removed jupyter_bokeh

Jenkinsfile, binder/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
This is to productize all the manual `pip install --user` we had to do to demo Era5 Raven notebook PR: https://github.com/Ouranosinc/raven/pull/200
birdy updated for Raven, then for Finch.
Pinning of pandas and geopandas is due to salem not supporting geopandas >= 0.7 as in this issue https://github.com/fmaussion/salem/issues/152 so can unpin once there are new release of salem.
scikit-image was also need by Raven notebook `gridded_data_subset.ipynb`.
The ipyleaflet marker do not display in Raven `Region_selection.ipynb` but can be moved and its coordinate can be extracted.
Not sure why, maybe relate to https://github.com/jupyter-widgets/ipyleaflet/issues/91.  Possibly also due to the freshly released jupyterlab-2.0 but downgrading jupyterlab means downgrading all the other jupyter …
=> jupyter docker: upgrade birdy, pin pandas and geopandas for Era5 Raven notebooks

notebooks/output-sanitize.cfg
Add regex sanitize for WPS output url.
Both production Jenkins (https://pavics.ouranos.ca/wpsoutputs/) and and non-production Travis-CI (http://localhost:5000/outputs/) WPS output url are accepted.  This means non-production url in notebooks won't be caught by Jenkins.  Don't like this, but no easy solution yet.
For Finch PR https://github.com/bird-house/finch/pull/112
Tested on Jenkins but un-tested on Travis-CI.
Passed Jenkins run http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/add-regex-to-output-sanitize-cfg-for-Travis-CI/5/console.
@davidcaron Can you help test this one on Travis-CI?
=> output-sanitize.cfg: try to make notebooks work on both Travis-CI and Jenkins

notebooks/output-sanitize.cfg
Blind fix for Pr https://github.com/bird-house/finch/pull/114/ since no
updated Finch server for testing.
New regex not adding more errors to Jenkins vs old Finch: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/output-sanitize-for-Finch-nb/2/console
=> output-sanitize.cfg: add temp folder from Finch notebook

notebooks/output-sanitize.cfg
@nilshempelmann here are the additional regexes for your FlyingPigeon PR https://github.com/bird-house/flyingpigeon/pull/321
Should handle
```
assert reference_output == test_output failed:
'<img src="ht...width="400"/>' == '<img src="ht...width="400"/>'
- <img src="http://127.0.0.1:8093/outputs/STATUS_FILE/tmpirlo_k7d.png" width="400"/>
?                                                        ^^  ----
+ <img src="http://127.0.0.1:8093/outputs/STATUS_FILE/tmplwz7aplo.png" width="400"/>
?                                                        ^^^^^^
```
=> Add more sanitize regex for flyingpigeon

Jenkinsfile, binder/Dockerfile, launchcontainer, launchnotebook
New build of our Jupyter env.
Required update to the notebooks for owslib and xarray breaking changes, see commit https://github.com/Ouranosinc/pavics-sdi/commit/08325cb64ff9b41ec578e2bc1855deb1debdbfc8 or PR https://github.com/Ouranosinc/pavics-sdi/pull/170.
```diff
<   - geopandas=0.6.2=py_0
>     - geopandas==0.7.0
<   - xarray=0.15.0=py_0
>   - xarray=0.15.1=py_0
<   - owslib=0.19.1=py_0
>   - owslib=0.19.2=py_1
<   - dask-core=2.12.0=py_0
>   - dask-core=2.15.0=py_0
<     - distributed==2.12.0
>     - distributed==2.15.0   
<     - xclim==0.14.0
>     - xclim==0.16.0
```
Full conda env export diff:
[200312-200427-conda-env-export.diff.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/4547396/200312-200427-conda-env-export.diff.txt)
Full new conda …
=> release: update to use image pavics/workflow-tests:200427

Jenkinsfile, binder/Dockerfile, docker/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
Now we do not need a separate docker build for the [`custom_climate_portraits`](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/tree/custom_climate_portraits) branch (PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/35).  That branch should only be used for notebook changes.  Jupyter env change should directly PR to `master`.
Did not add the full `holoviz` package since it seems to freeze the build (stuck in Solving Environment for more than 25 mins).
Also changed the base image to continuumio/miniconda3 since the previous one was deprecated.
Raven PR https://github.com/Ouranosinc/raven/pull/266 (commit https://github.com/Ouranosinc/raven/commit/0763bf52abec1bc0a70927de3a2dc2cc1cf77ec3) removed salem dependency and replaced with rioxarray.
salem was previously …
=> docker: new build to remove salem, replaced by rioxarray and add packages for the custom_climate_portraits branch

Jenkinsfile, binder/Dockerfile, docker/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
Deployed to https://medus.ouranos.ca/jupyter for testing.
Jenkins build passed http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-jupyter-extensions/2/console
Part of issue https://github.com/Ouranosinc/pavics-sdi/issues/141.
Added:
* https://github.com/hadim/jupyter-archive
Download entire folder as archive.
* https://blog.jupyter.org/a-visual-debugger-for-jupyter-914e61716559
* https://github.com/plotly/jupyter-dash
Develop Plotly Dash apps interactively from within Jupyter environments.
```diff
>   - jupyter-archive=0.6.2=py_0                                                                                                                      
>   - jupyter-dash=0.2.1.post1=py_0
<   - owslib=0.19.2=py_1
>   - owslib=0.20.0=py_0
>   - …
```
=> docker: new jupyter extensions: jupyter-archive, visual debugger, jupyter-dash

Jenkinsfile, binder/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
Pin hvplot for https://github.com/holoviz/hvplot/issues/498 (violin plot not working in latest hvplot 0.6.0).
Jenkins successful build: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-build-and-pin-pytest/4/console (with pavics-sdi PR https://github.com/Ouranosinc/pavics-sdi/pull/173).
```diff
<   - hvplot=0.6.0=pyh9f0ad1d_0
>   - hvplot=0.5.2=py_0
<   - dask=2.20.0=py_0
>   - dask=2.22.0=py_0
<   - geopandas=0.8.0=py_1
>   - geopandas=0.8.1=py_0
<   - pandas=1.0.5=py37h0da4684_0
>   - pandas=1.1.0=py37h3340039_0
<   - matplotlib=3.2.2=1
>   - matplotlib=3.3.0=1
<   - numpy=1.18.5=py37h8960a57_0
>   - numpy=1.19.1=py37h8960a57_0
<   - cryptography=2.9.2=py37hb09aad4_0
>   - cryptography=3.0=py37hb09aad4_0
<   - python=3.7.6=h8356626_5_cpython
> …
```
=> New docker build and pin old hvplot

Jenkinsfile, binder/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
Add handcalcs https://github.com/connorferster/handcalcs/ and unpin hvplot since pinning did not solve violin plot issue, see this comment https://github.com/bird-house/birdhouse-deploy/pull/63#issuecomment-668270608
Successful Jenkins build http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/periodic-rebuild-and-add-handcalcs/1/console
```diff
>     - handcalcs==0.8.1
<     - xclim==0.18.0
>     - xclim==0.19.0
<   - hvplot=0.5.2=py_0
>   - hvplot=0.6.0=pyh9f0ad1d_0
<   - dask=2.22.0=py_0
>   - dask=2.26.0=py_0
<   - bokeh=2.1.1=py37hc8dfbb8_0
>   - bokeh=2.2.1=py37hc8dfbb8_0
<   - numba=0.50.1=py37h0da4684_1
>   - numba=0.51.2=py37h9fdb41a_0
```
Full `conda env export` diff:
[200803-200914.1-conda-env-export.diff.txt](https://github.com/Ouranosinc/PAVICS-e2e-w …
=> docker: periodic rebuild and add handcalcs

Jenkinsfile, binder/Dockerfile, docker/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
```diff
>   - clisops=0.3.1=pyh32f6830_1
<     - xclim==0.19.0
>   - xclim=0.20.0=py_0
<   - xarray=0.16.0py_0
>   - xarray=0.16.1=py_0
<   - dask=2.26.0=py_0
>   - dask=2.27.0=py_0
<   - fiona=1.8.13=py37h0492a4a_1
>   - fiona=1.8.17=py37ha3d844c_0
<   - gdal=3.0.4=py37h4b180d9_10
>   - gdal=3.1.2=py37h518339e_2
<   - jupyter_server=0.1.1=py37_0
>   - jupyter_server=1.0.1=py37hc8dfbb8_0
>     - jupyternotify==0.1.15
>     - pytest-tornasync==0.6.0.post2
```
Passing Jenkins build: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/install-xclim-using-conda-to-pull-new-clisops/7/console
Full `conda env export` diff:
[200914.1-200925.1-conda-env-export.diff.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/5285928/200914.1-200925.1-conda-env-export …
=> docker: Install xclim using conda to pull new clisops

Jenkinsfile, binder/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
Python upgraded from 3.7 to 3.8.  Any possible potential problem? @huard @tlogan2000 
Jenkins build no new error except the known "WMS_example.ipynb: ​​neowms.sci.gsfc.nasa.gov ​​timed ​​out " http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-build-for-new-xclim/2/console
`memory_profiler` was for Pascal.
```diff
<   - python=3.7.8=h6f2ec95_1_cpython
>   - python=3.8.6=h852b56e_0_cpython
<   - xclim=0.20.0=py_0
>   - xclim=0.21.0=py_0
<   - dask=2.27.0=py_0
>   - dask=2.30.0=py_0
<   - rioxarray=0.0.31=py_0
>   - rioxarray=0.1.0=py_0
>   - memory_profiler=0.58.0=py_0
```
Full `conda env export` diff:
[200925.1-201026-conda-env-export.diff.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/5440884/200925.1-201026-conda-env-export.diff.txt) …
=> docker: new build for python 3.8, new xclim and memory_profiler

Jenkinsfile, binder/Dockerfile, docker/Dockerfile, docker/drive.jupyterlab-settings, docker/environment.yml, launchcontainer, launchnotebook
Adds 4 jupyterlab extensions to the docker image : jupytext, jupyterlab-google-drive, jupyter_conda and jupyterlab-git
```diff
>   - jupyter_conda=3.4.1=pyh9f0ad1d_0
>   - jupyterlab-git=0.22.3=pyhd8ed1ab_0
>   - jupytext=1.6.0=pyh9f0ad1d_0
<   - jupyterhub=1.1.0=py38h32f6830_5
>   - jupyterhub=1.2.1=py38h578d9bd_0
```
Passing Jenkins build: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/add-notebook-tools/9/console
Full `conda env export` diff:
[201026-201111-conda-env-export.diff.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/5527818/201026-201111-conda-env-export.diff.txt)
Full new `conda env export`:
[201111-conda-env-export.yml.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/5527819/201111-conda-env-export.yml.txt) …
=> docker: adds 4 jupyterlab extensions

Jenkinsfile, binder/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
`cfgrib` added for PR https://github.com/Ouranosinc/pavics-vdb/pull/21.
Jenkins build with known error only: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-build-with-cfgrib/2/console
Corresponding test fix https://github.com/Ouranosinc/pavics-sdi/pull/195.
Corresponding PR to deploy to PAVICS https://github.com/bird-house/birdhouse-deploy/pull/112.
```diff
>   - cfgrib=0.9.8.5=pyhd8ed1ab_0
<   - clisops=0.3.1=pyh32f6830_1
>   - clisops=0.4.0=pyhd3deb0d_0
<   - dask=2.30.0=py_0
>   - dask=2020.12.0=pyhd8ed1ab_0
<   - owslib=0.20.0=py_0
>   - owslib=0.21.0=pyhd8ed1ab_0
<   - xarray=0.16.1=py_0
>   - xarray=0.16.2=pyhd8ed1ab_0
<   - xclim=0.21.0=py_0
>   - xclim=0.22.0=pyhd8ed1ab_0
<   - jupyter_conda=3.4.1=pyh9f0ad1d_0
>   - …
```
=> docker: new build to get updates and add cfgrib

README.md, runtest
Small code change, fairly big impact here.  The README has the background.
Impact:
* (removed, will re-evaluate this next time) With the switch to `--nbval-lax` that disable output checking, some notebook failures might fly under the radar.  We have to audit all notebooks and add the `# NBVAL_CHECK_OUTPUT` to any cells that is critical to the correctness of the notebooks.
* With `.ncml` links always coming from our production `pavics.ouranos.ca` server, this means if the production server is down, tests will fail as well.  This means the tests are less "independent".
=> Avoid burden to copy .ncml files to server under test

Jenkinsfile, binder/Dockerfile, docker/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
* Added RavenPy and it's extra dependencies, causing python to downgrade from `3.8` to `3.7`
* Pin OWSLib for timeout bug
* Pin JupyterLab because latest version breaks the JupyterLab extensions we use
* Pin Cftime because it breaks Xarray
For matching PR that deploys this into PAVICS https://github.com/bird-house/birdhouse-deploy/pull/121
```diff
<   - python=3.8.6=h852b56e_0_cpython
>   - python=3.7.9=hffdb5ce_0_cpython
>     - ravenpy==0.2.3    
>   - statsmodels=0.12.1=py37h902c9e0_2
<   - xclim=0.22.0=pyhd8ed1ab_0
>   - xclim=0.23.0=pyhd8ed1ab_0
<     - birdhouse-birdy==0.6.9
>     - birdhouse-birdy==0.7.0
<   - cf_xarray=0.3.1=pyhd3deb0d_0
>   - cf_xarray=0.4.0=pyh44b312d_0
<   - clisops=0.4.0=pyhd3deb0d_0
>   - clisops=0.5.1=pyhd3deb0d_0
<   - …
```
=> docker: new build with ravenpy for raven notebooks

Jenkinsfile, binder/Dockerfile, docker/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
For regridding notebook, see https://github.com/Ouranosinc/pavics-sdi/pull/201#issuecomment-778329309.
Also unpin `owslib` (broke xarray) and `cftime` (timeout bug) pinned in previous release (https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/60).
This new Jupyter env is deployed to https://medus.ouranos.ca/jupyter so you can test out xESMF.
Jenkins build with Raven notebooks enabled: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/test-nbval-lax-DO_NOT_MERGE/13/console
That 12 mins 45 sec includes all Raven, Finch and Pavics-sdi notebooks.  It's against my devel server lvupavicsmaster.ouranos.ca since Boreas currently have a performance problem (https://github.com/bird-house/birdhouse-deploy/pull/123) and would take too long to run all Raven notebooks.
Raven …
=> docker: add xESMF to Jupyter env

notebooks/output-sanitize.cfg
For this regridding notebook https://github.com/Ouranosinc/pavics-sdi/blob/bbe3061dceb98688e9fd58836fbc50992ee31568/docs/source/notebooks/regridding.ipynb (PR https://github.com/Ouranosinc/pavics-sdi/pull/201) to pass Jenkins.
Double Jenkins run to be sure:
http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/update-nbval-sanitize-config-for-pavics-sdi-regridding-notebook/7/console
http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/update-nbval-sanitize-config-for-pavics-sdi-regridding-notebook/8/console
Jenkins passing also required https://github.com/bird-house/birdhouse-deploy/pull/132 and https://github.com/Ouranosinc/pavics-sdi/pull/206
=> Update nbval sanitize config for pavics sdi regridding notebook

runtest
Also harmonize with the proxy timeout here
https://github.com/bird-house/birdhouse-deploy/blob/7198ee378f6d123922d4b622fea5fb9eeb6743d7/birdhouse/default.env#L55-L57
Will also help for Raven notebooks since these are particularly heavy.
=> runtest: increase notebook timeout due to heavier new pavics-sdi regridding notebook

.gitignore, downloadrepos, testall
I created that branch and found out that notebooks were not found: 
https://github.com/Ouranosinc/pavics-sdi/tree/magpie-thredds+catalog-deprecate
Seems like archives replace everything else than alphanum and `-`, `_` to `-`, but still use the original chars (eg `+` in this case) for the URL reference. 
This PR replaces where necessary.
=> Branch chars

Jenkinsfile
It was agreed the default value was supposed to be `false` in comment
https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/55#issuecomment-736128455.
Another reason to keep this option to `false` by default, is this entire
Jenkins test suite also runs nightly on production instances so the admin
password on production instances will never be the default value, for security
reason, so this new notebook activated by `TEST_MAGPIE_AUTH` will never pass.
=> jenkins: set TEST_MAGPIE_AUTH default value to false

Jenkinsfile, README.md, launchcontainer, launchnotebook, runtest, testall
@huard we will be able to optionally provide `--nbval-lax` for Raven notebooks (will help for the up-coming Raven demo).
@MatProv I kept it a text box so we have the flexibility to add other `py.test` options later without having to modify the Jenkins UI again.
@fmigneault Your previous Branch chars PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/65, the `.` (dot) was also not replaced in the archive dir name.  Also had to escape the `-` since it is the "range" operator.
Tested here https://daccs-jenkins.crim.ca/job/PAVICS-e2e-workflow-tests/job/minor-fixes-launchnotebook-nbval-lax-as-option/2/parameters/ (using pavics-sdi branch `lvu-test.branch.name.with-dots` and activating Raven notebooks with `--nbval-lax`, targetting my lvupavicsdev.ouranos.ca with latest Finch and …
=> Jenkins: allow to customize py.test options for --nbval-lax and a few other minor fixes

Jenkinsfile, binder/Dockerfile, launchcontainer, launchnotebook
Matching PR to deploy to PAVICS: https://github.com/bird-house/birdhouse-deploy/pull/147
Jenkins all passed http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-build-for-raven-notebooks-demo/4/console (together with the new finch in the birdhouse-deploy PR above).
```diff
<   - ravenpy=0.3.1=py37_0
>   - ravenpy=0.4.1=py37_0
<   - xesmf=0.5.2=pyhd8ed1ab_0
>   - xesmf=0.5.3=pyhd8ed1ab_0 
<   - dash=1.19.0=pyhd8ed1ab_0
>   - dash=1.20.0=pyhd8ed1ab_0
```
Full diff of `conda env export`:
[210408-210414-conda-env-export.diff.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/6312821/210408-210414-conda-env-export.diff.txt)
Full new `conda env export`:
[210414-conda-env-export.yml.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/fi …
=> docker: rebuild to get latest RavenPy for Raven demo

conftest.py
Ignore by default html and javascript output to decrease usage of `NBVAL_IGNORE_OUTPUT`.
- Adds `conftest.py` following https://nbval.readthedocs.io/en/latest/index.html?highlight=skip#Skipping-certain-output-types
- Probably will avoid us needing `--nbval-lax`.
- Tested with Raven notebooks http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/nbval-default-ignore-html-and-javascript-output/2/console all diff from xarray html output are gone
Nbval documentation was not 100% correct: https://github.com/computationalmodelling/nbval/issues/168
=> Nbval default ignore html and javascript output

Jenkinsfile, binder/Dockerfile, docker/Dockerfile, docker/Dockerfile.testing, docker/environment.yml, launchcontainer, launchnotebook
New Jupyter env to get latest of everything, including ravenpy, birdy, xclim.
Jenkins build passing with updated Finch and Pavics-sdi notebooks: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-build-for-ravenpy/25/
Matching Finch notebook PR: https://github.com/bird-house/finch/pull/188
Matching Pavics-sdi notebook PR: https://github.com/Ouranosinc/pavics-sdi/pull/222
Matching PR to deploy this Jupyter env to PAVICS: https://github.com/bird-house/birdhouse-deploy/pull/175
Matching Raven notebook failure found https://github.com/Ouranosinc/raven/issues/392 (http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-build-for-ravenpy/14/console) and matching fix PR https://github.com/Ouranosinc/raven/pull/393 …
=> New docker build for ravenpy birdy xclim

Jenkinsfile, binder/Dockerfile, docker/Dockerfile.testing, docker/environment.yml, launchcontainer, launchnotebook, releasedocker
Add `intake-xarray` (fixes https://github.com/Ouranosinc/pavics-sdi/issues/223)
@huard @tlogan2000 also proactively add `intake-geopandas` and `intake-thredds` as they look interesting.  Tried to add `intake-stac` but got into conflicting dependencies during build so had to leave it out.
This is an incremental build (not a full build) from the previous release (https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/75) so only those are changed (so regression risk is extremely low):
```
package                    |            build                                                                                                     
---------------------------|----------------- …
```
=> New docker build for raven notebooks

Jenkinsfile, binder/Dockerfile, binder/reorg-notebooks, default_build_params, docker/Dockerfile, docker/Dockerfile.testing, downloadrepos, launchcontainer, launchnotebook, runtest, testall
- Add PAVICS homepage notebooks to Jenkins testsuite and those notebooks enabled by default.
- Also released new Jupyter build for the homepage notebook.  Only `unzip` is newly added to the Jupyter env.  No other update.
Matching required notebook changes PR https://github.com/Ouranosinc/PAVICS-landing/pull/29
Matching PAVICS PR deployment change to test this PR https://github.com/bird-house/birdhouse-deploy/pull/180
Matching PR to update pavics-landing deployment config https://github.com/bird-house/birdhouse-deploy-ouranos/pull/12
- Add new ability to force link to stay on `pavics.ouranos.ca` in notebooks.  Pavics homepage notebooks use a lot of .ncml so it was too much of .nc files to replicated to all the test servers.
- Homepage notebooks are also deployed on Binder under …
=> Add PAVICS homepage notebooks to Jenkins testsuite and new Jupyter env build

Jenkinsfile, binder/Dockerfile, docker/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
JupyterLab v3 was available since January 2021 but we had to pin to v2 since many of the plugins we use were broken at the time for v3.
Fast forward 7 months later, only the Google Drive plugin still do not support JupyterLab v3 so we decided to drop it since it was only used by one single user (`ls -larth  /data/jupyterhub_user_data/*/.home/.jupyter/lab/user-settings/@jupyterlab/google-drive /dev/null` shows who uses it).  We have not enabled the system-wide Google Drive config due to security concern so each user had to configure it themselves separately.
Staying on JupyterLab v2 caused us the reverse problem, some plugins stopped working with v2, example the jupyterlab-system-monitor one.  That one is becoming more crucial as we have more and more users and we would like users to be …
=> docker: update to JupyterLab v3 and fix broken jupyterlab-system-monitor plugin

runtest
Current implementation to change `pavics.ouranos.ca` to `boreas.ouranos.ca` was bit silly, done in a haste.
It causes diff problem when the url is printed back.
Relate to PR https://github.com/Ouranosinc/pavics-sdi/pull/225
```
_ pavics-sdi-fix-subset-user-input.ipynb-for-jenkins/docs/source/notebooks/subset-user-input.ipynb::Cell 12 _
Notebook cell execution failed
Cell 12: Cell outputs differ
Input:
catalog = "https://boreas.ouranos.ca/twitcher/ows/proxy/thredds/catalog/datasets/gridded_obs/catalog.xml"  # TEST_USE_PROD_DATA
cat = TDSCatalog(catalog)
data = cat.datasets[0].access_urls["OPENDAP"]
data
Traceback:
mismatch 'text/plain'
assert reference_output == test_output failed:
"'https://pav...rcan_v2.ncml'" == "'https://bor...rcan_v2.ncml'"
Skipping 72 identical trailing characters in …
```
=> Fix runtest to properly exclude regex replace pavics.ouranos.ca string

Jenkinsfile, binder/Dockerfile, docker/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
Biggest feature is support for bokeh png export by installing a full blown firefox and all needed X-libraries into the docker image.  The image size went from 7.44GB to 7.97GB.
Deployed to https://medus.ouranos.ca/jupyter for testing.
Other noticeable changes:
```diff
<   - ravenpy=0.7.0=pyh1bb2064_0
>   - ravenpy=0.7.4=pyh7f9bfb9_0
<   - xclim=0.28.0=pyhd8ed1ab_0
>   - xclim=0.28.1=pyhd8ed1ab_0
>   - geckodriver=0.29.1=h3146498_0
>   - selenium=3.141.0=py37h5e8e339_1002
>   - nested_dict=1.61=pyhd3deb0d_0
>   - paramiko=2.7.2=pyh9f0ad1d_0
>   - scp=0.14.0=pyhd8ed1ab_0
>   - s3fs=2021.8.1=pyhd8ed1ab_0
<   - pandas=1.3.1=py37h219a48f_0
>   - pandas=1.2.5=py37h219a48f_0
<   - owslib=0.24.1=pyhd8ed1ab_0
>   - owslib=0.25.0=pyhd8ed1ab_0
<   - cf_xarray=0.6.0=pyh6c4a22f_0
>   - …
```
=> docker: new jupyter for ravenpy and other new additions

Jenkinsfile
Add any variation of sub-dir notebooks for artifact collection in Jenkins.
For instance, following were omitted: 
https://github.com/Ouranosinc/pavics-sdi/tree/master/docs/source/notebook-components
At the same time, ensure following are not matched: 
https://github.com/Ouranosinc/pavics-sdi/tree/master/docs/source/deprecated
Useful for collecting results from https://github.com/bird-house/birdhouse-deploy/pull/114
=> collect missing notebooks artifacts in Jenkins

Jenkinsfile
- Adds check to avoid error on missing `buildout/*.output.ipynb` to archive artifact.
- Resolves https://github.com/bird-house/birdhouse-deploy/pull/220#issuecomment-960345953
- Fix regression from https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/91
=> avoid error on missing 'buildout/*.output.ipynb' to archive artifact

Jenkinsfile, binder/Dockerfile, conftest.py, docker/Dockerfile, docker/Dockerfile.testing, docker/environment.yml, launchcontainer, launchnotebook
Previously, when xclim and ravenpy were pinning their own dependencies, the pins were ignored and we had to manually repeat the same pins again.  See comment https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/94#issuecomment-996841873.
This PR allows xclim and ravenpy to manage their own dependencies pinning transparently during this Jupyter env rebuild.
Also fixed a long standing build performance along the way.  Build time went from 50 mins to 25 mins and builds on DockerHub works again.
Deployed as "beta" image on https://pavics.ouranos.ca/jupyter for testing.
- Switched to using mamba instead of conda since mamba dependency solver is faster.  Mamba solver being faster at the expense of less precision so had to pin latest xclim and ravenpy to avoid random downgrade in the 2nd …
=> docker: prevent manual pin of dependencies and improve build speed

Jenkinsfile, runtest
Set `TEST_NO_USE_PROD_DATA` to use all test data from system under test.
Useful to test future production server that will have all the huge datas.
Fixes https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/issues/103.
Relate to https://github.com/bird-house/finch/pull/232 and https://github.com/Ouranosinc/pavics-sdi/pull/254.
=> test framework: allow testing using all test data from system under test

Jenkinsfile, binder/Dockerfile, docker/Dockerfile, docker/Dockerfile.testing, docker/environment.yml, launchcontainer, launchnotebook
```diff
>   - pre-commit=2.17.0=py38h578d9bd_0
>   - xlrd=2.0.1=pyhd8ed1ab_3
<   - xclim=0.32.1=pyhd8ed1ab_0
>   - xclim=0.34.0=pyhd8ed1ab_0
<   - cfgrib=0.9.9.1=pyhd8ed1ab_1
>   - cfgrib=0.9.10.1=pyhd8ed1ab_0
<   - cftime=1.5.1.1=py38h6c62de6_1
>   - cftime=1.6.0=py38h3ec907f_0
<   - intake-xarray=0.5.0=pyhd8ed1ab_0
>   - intake-xarray=0.6.0=pyhd8ed1ab_0
<   - pandas=1.3.5=py38h43a58ef_0
>   - pandas=1.4.1=py38h43a58ef_0
<   - regionmask=0.8.0=pyhd8ed1ab_1
>   - regionmask=0.9.0=pyhd8ed1ab_0
<   - rioxarray=0.9.1=pyhd8ed1ab_0
>   - rioxarray=0.10.3=pyhd8ed1ab_0
<   - xarray=0.20.2=pyhd8ed1ab_0
>   - xarray=2022.3.0=pyhd8ed1ab_0
<   - zarr=2.10.3=pyhd8ed1ab_0
>   - zarr=2.11.1=pyhd8ed1ab_0
```
`dask` and `distributed` was causing …
=> New Jupyter env build with new xlrd, pre-commit, pin dask, distributed, cf_xarray, latest of everything else

Jenkinsfile, binder/Dockerfile, binder/test-notebooks/TEST-panel-binder.ipynb, binder/test-notebooks/TEST-panel-servable.ipynb, docker/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
Still have to pin `dask` for performance and `shapely` for notebook error.
Dask dashboard and Panel server app work both by manually mapping `http://localhost:<PORT>` to `https://pavics.ouranos.ca/jupyter/user/<USER>/proxy/<PORT>` as seen in screenshots below:
The "Render with Panel" green button also works and avoid having to deal with manual URL rewrite:
```diff
>   - dask-labextension=5.2.0=pyhd8ed1ab_0
>   - jupyter-panel-proxy=0.2.0a2=py_0
>   - jupyter-server-proxy=3.2.1=pyhd8ed1ab_0
<     - handcalcs==1.4.1
<   - xclim=0.34.0=pyhd8ed1ab_0
>   - xclim=0.36.0=pyhd8ed1ab_0
<   - cf_xarray=0.6.3=pyhd8ed1ab_0
>   - cf_xarray=0.7.2=pyhd8ed1ab_0
<   - clisops=0.8.0=pyh6c4a22f_0
>   - clisops=0.9.0=pyh6c4a22f_0
<   - pandas=1.4.1=py38h43a58ef_0
>   - pandas=1.3.5=py38h43a58ef_0
<   - …
```
=> docker: new build for new XClim and to get Dask dashboard and Panel server app to work

Jenkinsfile, binder/Dockerfile, docker/environment.yml, launchcontainer, launchnotebook
Full rebuild to add `urlpath`.  Previous rebuild was https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/106.
- Adds `urlpath` for https://github.com/Ouranosinc/pavics-sdi/pull/268, fixes https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/issues/110
- Relevant changes (alphabetical order):
```diff
<   - climpred=2.2.0=pyhd8ed1ab_0
>   - climpred=2.3.0=pyhd8ed1ab_0
<   - dask=2022.11.0=pyhd8ed1ab_0
>   - dask=2022.11.1=pyhd8ed1ab_0
<   - flox=0.6.3=pyhd8ed1ab_0
>   - flox=0.6.4=pyhd8ed1ab_0
<   - h5netcdf=1.0.2=pyhd8ed1ab_0
>   - h5netcdf=1.1.0=pyhd8ed1ab_0
<   - numpy=1.23.4=py38h7042d01_1
>   - numpy=1.23.5=py38h7042d01_0
>   - urlpath=1.2.0=pyhd8ed1ab_0
```
- Deployed as "alpha" image in production for bokeh visualization performance regression testing.
- Manual test …
=> New Jupyter env docker build for urlpath

Jenkinsfile
Because when Raven notebooks are added to the test run, the 1h timeout is busted.
See comment
https://github.com/bird-house/birdhouse-deploy/pull/203#issuecomment-1433920670
=> jenkins: bump full run timeout from 1h to 2h

notebooks/output-sanitize.cfg
Remove WPS name from output url for notebook testing
This replaces bird-house/finch#273 as a solution for the change in output paths in wps outputs.
The previous solution was breaking finch's CI. pyWPS wants "outputpath" and "outputurl" to match. This means that if "outputurl" has two levels, "outputpath" must have the same second level. But, when developing and testing (both locally and on the CI) "outputpath" is not explicitly set, thus is the default, thus does not match "outputurl"'s second level.  The previous solution was patching the notebooks directly when generating them, but nothing of the sort was done in the test suite, which then failed.
The proper way to fix this in the testing is this sanitizing file, thus I am suggesting to take care of the path issue here directly, and …
=> Remove WPS name in output paths

Jenkinsfile, binder/Dockerfile, docker/Dockerfile.testing, launchcontainer, launchnotebook
This is a build on top of an existing build.  A fresh full build because it would pull a newer RavenPy which would requires a newer RavenWPS, which do not start at this moment.
This incremental build is faster to test and will fix our failing Jenkins due to missing package `esgf-pyclient`.
It is annoying to have Jenkins failing since a while just for a missing package.
- Adds `esgf-pyclient` for esgf-dap.ipynb (https://github.com/Ouranosinc/pavics-sdi/pull/269)
- Adds `xncml` for gen_catalog refactoring (https://github.com/Ouranosinc/pavics-vdb/pull/46)
- Fixes annoying harmless error `ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/envs/birdy/share/proj failed`
- Jenkins: lower job retention duration since we now have separated jobs for nightly trigger and manual trigger
- …
=> Jupyter docker: incremental build to add esgf-pyclient and xncml to fix Jenkins failure

.github/PULL_REQUEST_TEMPLATE.md, Jenkinsfile, binder/Dockerfile, default_build_params, docker/Dockerfile.testing, docker/environment.yml, launchcontainer, launchnotebook
Incremental build to add SAlib for new RavenPY nb Sensitivity_analysis.ipynb https://github.com/CSHS-CWRA/RavenPy/pull/320.
Incremental build is chosen over full build to speed up release process, at the expense of not having the latest and greatest of everything.  Also because this new SAlib do not pull any new indirect dependencies which might cause incompatibility.
This PR fixes https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/issues/127.
- Update Github PR template for new docker build release.  To serve as reminder for other persons not used to release new Jupyter env docker images.  A lot of steps and testings are required to release a new Jupyter env docker image.
- Jenkins config: Raven default branch switched from `master` to `main`.  To fix Raven tutorial notebooks …
=> Jupyter docker: incremental build to add SAlib for new RavenPY nb Sensitivity_analysis.ipynb

Jenkinsfile, binder/Dockerfile, docker/Dockerfile.testing, docker/environment.yml, launchcontainer, launchnotebook
For Pascal's Atelier ARRIMÉ - UQAM
- Jupyter env changes:
- Relevant changes (alphabetical order):
```diff
>       - fstd2nc==0.20231105.0
```
- Deployed as "beta" image in production for bokeh visualization performance regression testing.
- Manual test notebook https://github.com/Ouranosinc/PAVICS-landing/blob/master/content/notebooks/climate_indicators/PAVICStutorial_ClimateDataAnalysis-5Visualization.ipynb for bokeh visualization performance and it looks fine.
- Jenkins build, only known errors:
- [job-PAVICS-e2e-workflow-tests-incremental-build-for-pascal-atelier-1-consoleText.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/13574365/job-PAVICS-e2e-workflow-tests-incremental-build-for-pascal-atelier-1-consoleText.txt)
- …
=> Jupyter docker: incremental build to add `fstd2nc` to convert RPN files (from Environment Canada) to netCDF files

Jenkinsfile, binder/Dockerfile, docker/Dockerfile.testing, launchcontainer, launchnotebook
Incremental build to get latest unreleased `threddsclient` for Thredds 5 compatibility, to get this specific commit https://github.com/bird-house/threddsclient/commit/441e7273abf7fee1cf4afcc2587c297cd56f750b.
Incremental build is chosen over full build to speed up release process, at the expense of not having the latest and greatest of everything. Also because this do not pull any new indirect dependencies which might cause incompatibility with existing packages.
- Jupyter env changes:
- Relevant changes (alphabetical order):
```diff
<   - threddsclient=0.4.2=py_0
>       - threddsclient==0.4.4
```
- Deployed as "beta" image in production for bokeh visualization performance regression testing.
- Manual test notebook https://github.com/Ouranosinc/PAVICS-landing/blob/master/content/notebooks …
=>  Jupyter docker: incremental build to get latest unreleased threddsclient for Thredds 5 compat

Jenkinsfile, runtest, test-override/geoserver-nb-only.include.sh
Add a new text box `CONFIG_OVERRIDE_SCRIPT_URL` so we can specify a URL to a script that can be sourced to alter any configs before starting the test run.
A sample script is provided to filter the notebooks for testing GeoServer only.  This greatly improve the turn over time by avoiding to run unrelated notebooks.  Was useful to test this PR https://github.com/bird-house/birdhouse-deploy/pull/348.
This custom script can be coming from any URL and change other configs than just the list of notebooks to run.
Default is no custom script URL, same as the current behavior.
@fmigneault excellent question:
I'm curious to better understand the use case to see if it is the right (and only) solution. 
The current (CRIM) birdhouse-deploy CI sources the `env.local` file, starts a test instance with …
=> Jenkins: Allow full custom config override

downloadrepos, runtest, test-override/jenkins-params-default.include.sh, test-override/jenkins-params-external-repos.include.sh, test-override/jenkins-params-geoserver-nb-only.include.sh, test-override/jenkins-params-raven-specific-nb.include.sh, testall
To be used together with https://github.com/Ouranosinc/jenkins-config/pull/17.
If Jenkins `env.local` contains `export DEFAULT_CONFIG_PARAMETERS_SCRIPT_URL="https://raw.githubusercontent.com/Ouranosinc/PAVICS-e2e-workflow-tests/refs/heads/master/test-override/jenkins-params-default.include.sh"` notebooks that are known to have problems will be skipped so that Jenkins do not fail for known reasons.
This is related to https://github.com/bird-house/birdhouse-deploy/issues/496.  If raven notebooks are enabled by default, then we need to blacklist one of them because that one never passed, see `test-override/jenkins-params-default.include.sh` (the file that Jenkins will be pointed to).  The raven notebook is finally disabled by this PR https://github.com/CSHS-CWRA/RavenPy/pull/460.
In this …
=> Add optional default config to disable some notebooks in Jenkins

Jenkinsfile, default_build_params, test-override/jenkins-params-raven-nb-only.include.sh
All raven and ravenpy notebooks are now passing without the need for `--nbval-lax`.
Before, with the need of `--nbval-lax`, we could not have raven nbs running along-side of other notebooks that do not need `--nbval-lax`.
`--nbval-lax` option is for the entire run, it could not be specified per notebook.
Fixes https://github.com/bird-house/birdhouse-deploy/issues/496
=> jenkins: enable raven and ravenpy nbs by default in nightly builds

Jenkinsfile, notebooks/output-sanitize.cfg, test-override/jenkins-params-enable-nbval-skip.include.sh, test-override/jenkins-params-external-repos.include.sh, test-override/jenkins-params-readonly-checkout.include.sh
* Double timeout and slight decrease of build retention because RavenPy notebooks are enabled by default so it takes longer to run and artifacts size will be bigger.
* Add more override so we can create custom pipeline for special cases, see https://github.com/Ouranosinc/jenkins-config/pull/18
=> Additional Jenkins overrides for special case pipelines

test-override/jenkins-params-default.include.sh
This blacklist can be lifted once https://github.com/Ouranosinc/pavics-sdi/issues/353 is fixed.
Edit: We do not need this blacklist anymore.  The notebook restarted working, see https://github.com/Ouranosinc/pavics-sdi/pull/355.  We can still merge this PR for a nicer blacklisting mechanism.
=> test-override: update default blacklist mechanism to be simpler

.github/PULL_REQUEST_TEMPLATE.md, docker/Dockerfile, docker/Dockerfile.testing, docker/README.md, docker/environment.yml
This PR removes the remaining `PyPI`-provided packages from the build environment, allowing us to solely leverage `conda-forge` when generating our PAVICS kernels.
`figanos` was previously pinning `numpy` below v2.0, causing the environment to reinstall an older, `PyPI`-provided `numpy`. This is no longer the case (with `figanos>=0.5.0`).
- Removed `ipython_blocking` (obselete/unused)
- Replaced `figanos` (v0.4.0) and `xncml` (v0.4.0) `PyPI`-provided packages with their `conda-forge` package equivalents (v0.5.0 for both). 
- Updated the Pull Request templates to remove obsolete entries and clarify a few steps.
=> Drop PyPI packages from Jupter environment
